# What does this integration do?
# When a commit is pushed to the repo, the integration runs .NET tests
# (You can also run the tests manually, if you want that for some reason)
# - JustArion 18/02/25

name: Test Runner

on:
  workflow_dispatch:
  push:

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  run-tests:
    name: Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.X'
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - run: make restore

      - name: Run Project Tests
        run: make test